def CstDefineBackroundMaterial(mws, XminSpace, XmaxSpace, YminSpace, YmaxSpace, ZminSpace, ZmaxSpace):
    background = mws.Background
    material = mws.Material

    background.ResetBackground()
    background.Type('Normal')
    background.Epsilon('1.0')
    background.Mu('1.0')
    background.XminSpace(str(XminSpace))
    background.XmaxSpace(str(XmaxSpace))
    background.YminSpace(str(YminSpace))
    background.YmaxSpace(str(YmaxSpace))
    background.ZminSpace(str(ZminSpace))
    background.ZmaxSpace(str(ZmaxSpace))

    material.Reset()
    material.FrqType('all')
    material.Type('Normal')
    material.MaterialUnit('Frequency', 'Hz')
    material.MaterialUnit('Geometry', 'm')
    material.MaterialUnit('Time', 's')
    material.MaterialUnit('Temperature', 'Kelvin')
    material.Epsilon('1.0')
    material.Mue('1.0')
    material.Sigma('0.0')
    material.TanD('0.0')
    material.TanDFreq('0.0')
    material.TanDGiven('False')
    material.TanDModel('ConstSigma')
    material.EnableUserConstTanDModelOrderEps('False')
    material.ConstTanDModelOrderEps('1')
    material.SetElParametricConductivity('False')
    material.ReferenceCoordSystem('Global')
    material.CoordSystemType('Cartesian')
    material.SigmaM('0')
    material.TanDM('0.0')
    material.TanDMFreq('0.0')
    material.TanDMGiven('False')
    material.TanDMModel('ConstSigma')
    material.EnableUserConstTanDModelOrderMue('False')
    material.ConstTanDModelOrderMue('1')
    material.SetMagParametricConductivity('False')
    material.DispModelEps('None')
    material.DispModelMue('None')
    material.DispersiveFittingSchemeEps('Nth Order')
    material.MaximalOrderNthModelFitEps('10')
    material.ErrorLimitNthModelFitEps('0.1')
    material.UseOnlyDataInSimFreqRangeNthModelEps('False')
    material.DispersiveFittingSchemeMue('Nth Order')
    material.MaximalOrderNthModelFitMue('10')
    material.ErrorLimitNthModelFitMue('0.1')
    material.UseOnlyDataInSimFreqRangeNthModelMue('False')
    material.UseGeneralDispersionEps('False')
    material.UseGeneralDispersionMue('False')
    material.NLAnisotropy('False')
    material.NLAStackingFactor('1')
    material.NLADirectionX('1')
    material.NLADirectionY('0')
    material.NLADirectionZ('0')
    material.Rho('0.0')
    material.ThermalType('Normal')
    material.ThermalConductivity('0.0')
    material.HeatCapacity('0.0')
    material.MetabolicRate('0')
    material.BloodFlow('0')
    material.VoxelConvection('0')
    material.MechanicsType('Unused')
    material.Colour('0.6', '0.6', '0.6')
    material.Wireframe('False')
    material.Reflection('False')
    material.Allowoutline('True')
    material.Transparentoutline('False')
    material.Transparency('0')
    material.ChangeBackgroundMaterial()
