def CstTDMMeshSettings(mws, CellsPerWavelenth, MinimumCell):
    mesh = mws.Mesh
    meshSettings = mws.MeshSettings
    discretizer = mws.Discretizer

    mesh.MeshType('PBA')
    mesh.SetCreator('High Frequency')  # warning

    meshSettings.SetMeshType('Hex')
    meshSettings.Set('Version', '1%')
    meshSettings.Set.StepsPerWaveNear(str(CellsPerWavelenth))
    meshSettings.Set.StepsPerWaveFar(str(CellsPerWavelenth))
    meshSettings.Set.WavelengthRefinementSameAsNear('1')
    meshSettings.Set.StepsPerBoxNear(str(CellsPerWavelenth))
    meshSettings.Set.StepsPerBoxFar(str(CellsPerWavelenth))
    meshSettings.Set.MaxStepNear(str(CellsPerWavelenth))
    meshSettings.Set.MaxStepFar(str(CellsPerWavelenth))
    meshSettings.Set.ModelBoxDescrNear('maxedge')
    meshSettings.Set.ModelBoxDescrFar('maxedge')
    meshSettings.Set.UseMaxStepAbsolute('0')
    meshSettings.Set.GeometryRefinementSameAsNear('1')
    meshSettings.Set.UseRatioLimitGeometry('1')
    meshSettings.Set.RatioLimitGeometry(str(MinimumCell))
    meshSettings.Set.MinStepGeometryX('0')
    meshSettings.Set.MinStepGeometryY('0')
    meshSettings.Set.MinStepGeometryZ('0')
    meshSettings.Set.UseSameMinStepGeometryXYZ('1')
    meshSettings.SetMeshType('Hex')
    meshSettings.Set.FaceRefinementOn('0')
    meshSettings.Set.FaceRefinementPolicy('2')
    meshSettings.Set.FaceRefinementRatio('2')
    meshSettings.Set.FaceRefinementStep('0')
    meshSettings.Set.FaceRefinementNSteps('2')
    meshSettings.Set.EllipseRefinementOn('0')
    meshSettings.Set.EllipseRefinementPolicy('2')
    meshSettings.Set.EllipseRefinementRatio('2')
    meshSettings.Set.EllipseRefinementStep('0')
    meshSettings.Set.EllipseRefinementNSteps('2')
    meshSettings.Set.FaceRefinementBufferLines('3')
    meshSettings.Set.EdgeRefinementOn('1')
    meshSettings.Set.EdgeRefinementPolicy('1')
    meshSettings.Set.EdgeRefinementRatio('2')
    meshSettings.Set.EdgeRefinementStep('0')
    meshSettings.Set.EdgeRefinementBufferLines('3')
    meshSettings.Set.RefineEdgeMaterialGlobal('0')
    meshSettings.Set.RefineAxialEdgeGlobal('0')
    meshSettings.Set.BufferLinesNear('3')
    meshSettings.Set.UseDielectrics('1')
    meshSettings.Set.EquilibrateOn('0')
    meshSettings.Set.Equilibrate('1.5')
    meshSettings.Set.IgnoreThinPanelMaterial('0')
    meshSettings.SetMeshType('Hex')
    meshSettings.Set.SnapToAxialEdges('1')
    meshSettings.Set.SnapToPlanes('1')
    meshSettings.Set.SnapToSpheres('1')
    meshSettings.Set.SnapToEllipses('1')
    meshSettings.Set.SnapToCylinders('1')
    meshSettings.Set.SnapToCylinderCenters('1')
    meshSettings.Set.SnapToEllipseCenters('1')

    discretizer.MeshType('PBA')
    discretizer.PBAType('Fast PBA')
    discretizer.AutomaticPBAType('True')
    discretizer.FPBAAccuracyEnhancement('enable')
    discretizer.ConnectivityCheck('False')
    discretizer.ConvertGeometryDataAfterMeshing('True')
    discretizer.UsePecEdgeModel('True')
    discretizer.GapDetection('False')
    discretizer.FPBAGapTolerance('1e-3')
    discretizer.SetMaxParallelMesherThreads('Hex', '12')
    discretizer.SetParallelMesherMode('Hex', 'Maximum')
    discretizer.PointAccEnhancement('0')
    discretizer.UseSplitComponents('True')
    discretizer.EnableSubgridding('False')
    discretizer.PBAFillLimit('99')
    discretizer.AlwaysExcludePec('False')
