def CstExportFarfieldSource(mws, exportpath, frequency):
    farfieldPlot = mws.FarfieldPlot

    farfieldPlot.Plottype('3D')
    farfieldPlot.Vary('angle2')
    farfieldPlot.Theta('90')
    farfieldPlot.Phi('90')
    farfieldPlot.Step('5')
    farfieldPlot.Step2('5')
    farfieldPlot.SetLockSteps('False')
    farfieldPlot.SetPlotRangeOnly('False')
    farfieldPlot.SetThetaStart('0')
    farfieldPlot.SetThetaEnd('180')
    farfieldPlot.SetPhiStart('0')
    farfieldPlot.SetPhiEnd('360')
    farfieldPlot.SetTheta360('False')
    farfieldPlot.SymmetricRange('False')
    farfieldPlot.SetTimeDomainFF('False')
    farfieldPlot.SetFrequency(str(frequency))
    farfieldPlot.SetTime('0')
    farfieldPlot.SetColorByValue('True')
    farfieldPlot.DrawStepLines('False')
    farfieldPlot.DrawIsoLongitudeLatitudeLines('False')
    farfieldPlot.ShowStructure('False')
    farfieldPlot.SetStructureTransparent('False')
    farfieldPlot.SetFarfieldTransparent('False')
    farfieldPlot.SetSpecials('enablepolarextralines')
    farfieldPlot.SetPlotMode('efield')
    farfieldPlot.Distance('1')
    farfieldPlot.UseFarfieldApproximation('True')
    farfieldPlot.SetScaleLinear('True')
    farfieldPlot.SetLogRange('40')
    farfieldPlot.SetLogNorm('0')
    farfieldPlot.DBUnit('0')
    farfieldPlot.EnableFixPlotMaximum('False')
    farfieldPlot.SetFixPlotMaximumValue('1')
    farfieldPlot.SetInverseAxialRatio('False')
    farfieldPlot.SetAxesType('user')
    farfieldPlot.SetAntennaType('unknown')
    farfieldPlot.Phistart('1.000000e+000', '0.000000e+000', '0.000000e+000')
    farfieldPlot.Thetastart('0.000000e+000', '0.000000e+000', '1.000000e+000')
    farfieldPlot.PolarizationVector('0.000000e+000', '1.000000e+000', '0.000000e+000')
    farfieldPlot.SetCoordinateSystemType('spherical')
    farfieldPlot.SetAutomaticCoordinateSystem('True')
    farfieldPlot.SetPolarizationType('linear')
    farfieldPlot.SlantAngle('0.000000e+000')
    farfieldPlot.Origin('bbox')
    farfieldPlot.Userorigin('0.000000e+000', '0.000000e+000', '0.000000e+000')
    farfieldPlot.SetUserDecouplingPlane('False')
    farfieldPlot.UseDecouplingPlane('False')
    farfieldPlot.DecouplingPlaneAxis('x')
    farfieldPlot.DecouplingPlanePosition('0.000000e+000')
    farfieldPlot.LossyGround('False')
    farfieldPlot.GroundEpsilon('1')
    farfieldPlot.GroundKappa('0')
    farfieldPlot.EnablePhaseCenterCalculation('False')
    farfieldPlot.SetPhaseCenterAngularLimit('3.000000e+001')
    farfieldPlot.SetPhaseCenterComponent('boresight')
    farfieldPlot.SetPhaseCenterPlane('both')
    farfieldPlot.ShowPhaseCenter('True')
    farfieldPlot.StoreSettings

    selectTreeItem = mws.SelectTreeItem(chr('Farfields\Farfield' + str(frequency) + {' '} + '[1]'))

    farfieldPlot.ASCIIExportAsSource(exportpath)
