def CstAir(mws):
    material = mws.Material

    material.Reset
    material.Name('Air')
    material.FrqType('all')
    material.Type('Normal')
    material.MaterialUnit('Frequency', 'GHz')
    material.MaterialUnit('Geometry', 'mm')
    material.Epsilon('1.00059')
    material.Mu('1.0')
    material.Kappa('0.0')
    material.TanD('0.0')
    material.TanDFreq('0.0')
    material.TanDGiven('False')
    material.TanDModel('ConstKappa')
    material.KappaM('0')
    material.TanDM('0.0')
    material.TanDMFreq('0.0')
    material.TanDMGiven('False')
    material.TanDMModel('ConstKappa')
    material.DispModelEps('None')
    material.DispModelMu('None')
    material.DispersiveFittingSchemeEps('General 1st')
    material.DispersiveFittingSchemeMu('General 1st')
    material.UseGeneralDispersionEps('False')
    material.UseGeneralDispersionMu('False')
    material.Rho('1.204')
    material.ThermalType('Normal')
    material.ThermalConductivity('0.026')
    material.HeatCapacity('1.005')
    material.SetActiveMaterial('all')
    material.Colour('0.682353', '0.717647', '1')
    material.Wireframe('False')
    material.Transparency('0')
    material.Create
    format(material)
