def CstCopperAnnealedLossy(mws):
    material = mws.Material
    material.Reset()
    material.Name('Copper (annealed)')
    material.FrqType('static')
    material.Type('Normal')
    material.SetMaterialUnit('Hz', 'mm')
    material.Epsilon('1')
    material.Mue('1.0')
    material.Kappa('5.8e+007')
    material.TanD('0')
    material.TanDFreq('0.0')
    material.TanDGiven('False')
    material.TanDModel('ConstTanD')
    material.KappaM('0.0')
    material.TanDM('0.0')
    material.TanDMFreq('0.0')
    material.TanDMGiven('False')
    material.TanDMModel('ConstTanD')
    material.DispModelEps('None')
    material.DispModelMue('None')
    material.DispersiveFittingSchemeEps('Nth Order')
    material.DispersiveFittingSchemeMue('Nth Order')
    material.UseGeneralDispersionEps('False')
    material.UseGeneralDispersionMue('False')
    material.FrqType('all')
    material.Type('Lossy metal')
    material.SetMaterialUnit('GHz', 'mm')
    material.Mue('1.0')
    material.Kappa('5.8e+007')
    material.Rho('8930.0')
    material.ThermalType('Normal')
    material.ThermalConductivity('401.0')
    material.HeatCapacity('0.39')
    material.MetabolicRate('0')
    material.BloodFlow('0')
    material.VoxelConvection('0')
    material.MechanicsType('Isotropic')
    material.YoungsModulus('120')
    material.PoissonsRatio('0.33')
    material.ThermalExpansionRate('17')
    material.Colour('1', '1', '0')
    material.Wireframe('False')
    material.Reflection('False')
    material.Allowoutline('True')
    material.Transparentoutline('False')
    material.Transparency('0')
    material.Create()
    format(material)
