def CstFR4lossy(mws):
    material = mws.material

    material.Reset()
    material.Name('FR-4 (lossy)')
    material.FrqType('all')
    material.Type('Normal')
    material.SetMaterialUnit('GHz', 'mm')
    material.Epsilon('4.3')
    material.Mue('1.0')
    material.Kappa('0.0')
    material.TanD('0.025')
    material.TanDFreq('10.0')
    material.TanDGiven('True')
    material.TanDModel('ConstTanD')
    material.KappaM('0.0')
    material.TanDM('0.0')
    material.TanDMFreq('0.0')
    material.TanDMModel('ConstKappa')
    material.DispModelEps('None')
    material.DispModelMue('None')
    material.DispersiveFittingSchemeEps('General 1st')
    material.DispersiveFittingSchemeMue('General 1st')
    material.UseGeneralDispersionEps('False')
    material.UseGeneralDispersionMue('False')
    material.Rho('0.0')
    material.ThermalType('Normal')
    material.ThermalConductivity('0.3')
    material.SetActiveMaterial('all')
    material.Colour('0.94', '0.82', '0.76')
    material.Wireframe('False')
    material.Transparency('0')
    material.Create()
    format(material)
